refs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -117.9712
  - 35.7108
  - 6
description: ''
format: "png8:m=h"
interactivity_layer: firep13_2
Layer: ''
maxzoom: 13
minzoom: 6
name: ''
source: "tmsource:///usr/local/share/mapbox-projects/firep13_2.tm2source"
styles:
  - style.mss
template: |-
  <strong>fire name: {{fire_name}}</strong>
  <small>agency: {{agency}}</small>
  <small>alarm date: {{alarm_date}}</small>
  {{#cont_date}}
  <small>cont date: {{cont_date}}</small>
  {{/cont_date}}  
  <small>gis acres: {{gis_acres}}</small>
  <small>year: {{year}}</small>
  <small>cause: {{cause}}</small>

